# Generated by Django 5.0.1 on 2024-02-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="review",
        ),
    ]
