# Generated by Django 5.0.1 on 2024-02-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="reviewModel",
            new_name="review",
        ),
    ]
