# Generated by Django 5.0.1 on 2024-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_review_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="service",
            field=models.CharField(max_length=100),
        ),
    ]
