# Generated by Django 5.0.1 on 2024-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_review_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
