# Generated by Django 5.0.1 on 2024-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_review_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_text",
            field=models.TextField(null=True),
        ),
    ]
