# Generated by Django 5.0.1 on 2024-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_review_review_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
