# Generated by Django 5.0.1 on 2024-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_review_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.CharField(max_length=100),
        ),
    ]
