# Generated by Django 5.0.1 on 2024-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_review_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="name",
            field=models.CharField(
                error_messages={"required": "Будь ласка вкажіть ваше ім'я"},
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.CharField(
                error_messages={"required": "Будь ласка оцініть сервіс"}, max_length=100
            ),
        ),
    ]
